# Generated by Django 2.2 on 2019-07-11 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntext', models.CharField(blank=True, max_length=20, null=True)),
                ('name_m', models.CharField(default='', max_length=20)),
                ('todayptno', models.IntegerField(blank=True, default='', null=True)),
                ('gongdan', models.IntegerField(blank=True, default='0', null=True)),
                ('jongham', models.IntegerField(blank=True, default='0', null=True)),
                ('vaccine', models.IntegerField(blank=True, default='0', null=True)),
                ('cashincome', models.IntegerField(blank=True, default='0', null=True)),
                ('creditincome', models.IntegerField(blank=True, default='0', null=True)),
                ('misu', models.IntegerField(blank=True, default='0', null=True)),
                ('totalincome', models.IntegerField(blank=True, default='0', null=True)),
                ('jichulcash', models.IntegerField(blank=True, default='0', null=True)),
                ('cashremain', models.IntegerField(blank=True, default='0', null=True)),
                ('cashsije', models.IntegerField(blank=True, default='0', null=True)),
                ('jichulclass', models.CharField(blank=True, default='없음', max_length=120, null=True)),
                ('jichulclass2', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('jichulclass3', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('jichulclass4', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('jichulclass5', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('jichulcontents', models.CharField(blank=True, default='없음', max_length=150, null=True)),
                ('jichulcontents2', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('jichulcontents3', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('jichulcontents4', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('jichulcontents5', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('jichulmoney', models.IntegerField(blank=True, default='0', null=True)),
                ('jichulmoney2', models.IntegerField(blank=True, default='', null=True)),
                ('jichulmoney3', models.IntegerField(blank=True, default='', null=True)),
                ('jichulmoney4', models.IntegerField(blank=True, default='', null=True)),
                ('jichulmoney5', models.IntegerField(blank=True, default='', null=True)),
                ('bigo', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('bigo2', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('bigo3', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('bigo4', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('bigo5', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('jichulsum', models.IntegerField(blank=True, default='0', null=True)),
                ('guneu', models.CharField(blank=True, default='없음', max_length=200, null=True)),
                ('guneu2', models.CharField(blank=True, default='', max_length=190, null=True)),
                ('guneu3', models.CharField(blank=True, default='', max_length=190, null=True)),
                ('guneu4', models.CharField(blank=True, default='', max_length=190, null=True)),
                ('guneu5', models.CharField(blank=True, default='', max_length=190, null=True)),
                ('dutyonoff', models.CharField(blank=True, default='무', max_length=100, null=True)),
                ('dutyonoff2', models.CharField(blank=True, default='', max_length=110, null=True)),
                ('dutyonoff3', models.CharField(blank=True, default='', max_length=110, null=True)),
                ('dutyonoff4', models.CharField(blank=True, default='', max_length=110, null=True)),
                ('dutyonoff5', models.CharField(blank=True, default='', max_length=110, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(blank=True, default='없음', max_length=100, null=True)),
            ],
        ),
    ]
